title: CV Andrei Martianov
description: Developer CV.
url: https://wake0up0ne0.github.io/CV
baseurl: ""
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-minifier

exclude:
  - docker-compose.yml
